# Generated by Django 4.2.6 on 2024-04-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('english', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('science', models.IntegerField()),
                ('hindi', models.IntegerField()),
                ('telugu', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
