# Generated by Django 4.2.6 on 2024-05-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
