# Generated by Django 4.2.6 on 2024-05-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('stadd_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='staff_photos')),
            ],
        ),
    ]
